name: "3Dash"
version: "1.0.5"
slug: "3dash"
description: "3D Dashboard for Home Assistant"
url: "https://github.com/kdcius/3Dash_webapp"
arch:
  - amd64
  - aarch64
  - armv7
ingress: true
ingress_port: 8099
panel_icon: "mdi:home-floor-3"
panel_title: "3Dash"
ports:
  8099/tcp: null
ports_description:
  8099/tcp: "Web interface"
init: false
startup: "application"
boot: "auto"
options: {}
schema: {}
